server:
  port: 8000

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: factory-coupon-service
          uri: http://localhost:10001/
          predicates:
            - Path=/api/v1/coupons/**
        - id: factory-product-service
          uri: http://localhost:10002/
          predicates:
            - Path=/api/v1/products/**
        - id: factory-issuance-service
          uri: http://localhost:10003/
          predicates:
            - Path=/api/v1/issuance/**
      httpclient:
        connect-timeout: 10000
        response-timeout: 10s
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true

eureka:
  instance:
    instance-id: gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
